/**
 * [INPUT]: VideoScript + DesignProfile + StyleComposition + assets (vo, bgm)
 * [OUTPUT]: Hyperframes project directory ready for `hyperframes render`
 * [POS]: scripts/ pipeline 第 [6] 步; 生成符合 hyperframes 规范的项目目录
 * [PROTOCOL]: 变更时更新此头部，然后检查 SKILL.md
 */

// ================================================================
//  Composer — generates a Hyperframes project directory
//
//  Hyperframes expects a project DIRECTORY (not a single HTML file)
//  containing:
//    - index.html       (main composition)
//    - hyperframes.json (registry + paths config)
//    - meta.json        (project metadata)
//    - assets/          (VO, BGM, images)
//
//  Hyperframes hard rules (from CLAUDE.md generated by hyperframes init):
//    1. Every timed element needs data-start / data-duration / data-track-index
//    2. Timed elements MUST have class="clip"
//    3. Timeline must be paused and registered on window.__timelines["main"]
//    4. Videos use muted attribute with separate <audio> element
//    5. NO Date.now(), Math.random(), or network fetches (deterministic only)
//    6. Root: <div id="root" data-composition-id="main"
//             data-start data-duration data-width data-height>
// ================================================================

import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { basename, join } from "path";
import type {
  BgmAsset,
  DesignProfile,
  Format,
  StyleComposition,
  VideoScript,
  VoAsset,
} from "./types.ts";

export interface ComposeInput {
  script: VideoScript;
  designProfile: DesignProfile;
  composition: StyleComposition;
  voAsset?: VoAsset;
  bgmAsset?: BgmAsset;
  projectDir: string; // directory to create
  projectName?: string;
}

const DIMENSIONS: Record<Format, { width: number; height: number }> = {
  "16:9": { width: 1920, height: 1080 },
  "9:16": { width: 1080, height: 1920 },
  "1:1": { width: 1080, height: 1080 },
  "4:5": { width: 1080, height: 1350 },
};

// ----------------------------------------------------------------
//  Public: build a complete Hyperframes project directory
// ----------------------------------------------------------------

export function buildHyperframesProject(input: ComposeInput): string {
  const { projectDir, composition, voAsset, bgmAsset } = input;
  const projectName = input.projectName ?? basename(projectDir);

  // 1. Create directories
  mkdirSync(projectDir, { recursive: true });
  const assetsDir = join(projectDir, "assets");
  mkdirSync(assetsDir, { recursive: true });

  // 2. Copy VO + BGM assets if present
  let voAssetRel: string | undefined;
  let bgmAssetRel: string | undefined;
  if (voAsset && existsSync(voAsset.path)) {
    const dest = join(assetsDir, "vo.wav");
    copyFileSync(voAsset.path, dest);
    voAssetRel = "assets/vo.wav";
  }
  if (bgmAsset && existsSync(bgmAsset.path)) {
    const dest = join(assetsDir, "bgm.mp3");
    copyFileSync(bgmAsset.path, dest);
    bgmAssetRel = "assets/bgm.mp3";
  }

  // 3. Write hyperframes.json (registry + paths config)
  writeFileSync(
    join(projectDir, "hyperframes.json"),
    JSON.stringify(
      {
        $schema: "https://hyperframes.heygen.com/schema/hyperframes.json",
        registry: "https://raw.githubusercontent.com/heygen-com/hyperframes/main/registry",
        paths: {
          blocks: "compositions",
          components: "compositions/components",
          assets: "assets",
        },
      },
      null,
      2
    )
  );

  // 4. Write meta.json
  writeFileSync(
    join(projectDir, "meta.json"),
    JSON.stringify(
      {
        id: projectName,
        name: projectName,
        createdAt: new Date().toISOString(),
      },
      null,
      2
    )
  );

  // 5. Write index.html (the actual composition)
  const html = buildIndexHtml({
    ...input,
    voAssetRel,
    bgmAssetRel,
  });
  writeFileSync(join(projectDir, "index.html"), html);

  return projectDir;
}

// ----------------------------------------------------------------
//  Index HTML builder
// ----------------------------------------------------------------

interface BuildHtmlInput extends ComposeInput {
  voAssetRel?: string;
  bgmAssetRel?: string;
}

function buildIndexHtml(input: BuildHtmlInput): string {
  const { script, designProfile, composition, voAssetRel, bgmAssetRel } = input;
  const dims = DIMENSIONS[composition.format];
  const { width, height } = dims;
  const totalDuration = composition.durationSeconds;

  const headingFont = designProfile.fonts.heading;
  const bodyFont = designProfile.fonts.body;
  const bgColor = designProfile.backgroundColor ?? "#0a0a0a";
  const textColor = designProfile.textColor ?? "#fafafa";

  // Build clips from script scenes
  let cursor = 0;
  const sceneClips: string[] = [];
  const tweens: string[] = [];

  for (const scene of script.scenes) {
    const start = cursor;
    const dur = scene.durationSeconds;
    const sceneId = `scene-${scene.index}`;
    sceneClips.push(buildSceneClip(sceneId, scene, start, dur, designProfile));
    // GSAP tween: fade in 0.3s from start, fade out 0.3s before end.
    // After exit, hard-kill opacity at clip end so non-linear seeking
    // (hyperframes is seekable) doesn't leave stale visibility state.
    tweens.push(
      `      tl.fromTo("#${sceneId}", { opacity: 0 }, { opacity: 1, duration: 0.3 }, ${start.toFixed(2)});`
    );
    if (dur > 0.6) {
      const exitStart = (start + dur - 0.3).toFixed(2);
      const exitEnd = (start + dur).toFixed(2);
      tweens.push(
        `      tl.to("#${sceneId}", { opacity: 0, duration: 0.3 }, ${exitStart});`
      );
      tweens.push(
        `      tl.set("#${sceneId}", { opacity: 0 }, ${exitEnd});`
      );
    }
    cursor += dur;
  }

  // Audio elements (VO + BGM) — separate <audio> tags per hyperframes spec
  const audioElements: string[] = [];
  if (voAssetRel) {
    audioElements.push(
      `    <audio class="clip" id="vo-track" src="${voAssetRel}" data-start="0" data-duration="${totalDuration}" data-track-index="50" preload="auto"></audio>`
    );
  }
  if (bgmAssetRel) {
    audioElements.push(
      `    <audio class="clip" id="bgm-track" src="${bgmAssetRel}" data-start="0" data-duration="${totalDuration}" data-track-index="40" preload="auto" volume="0.3"></audio>`
    );
  }

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=${width}, height=${height}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=${encodeFont(headingFont)}:wght@300;400;500;600;700&family=${encodeFont(bodyFont)}:wght@300;400;500;600&display=swap" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body {
        margin: 0;
        width: ${width}px;
        height: ${height}px;
        overflow: hidden;
        background: ${bgColor};
        color: ${textColor};
        font-family: '${bodyFont}', sans-serif;
      }
      .scene {
        position: absolute;
        inset: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        padding: ${composition.format === "9:16" ? "120px 60px" : "80px 120px"};
      }
      .heading {
        font-family: '${headingFont}', sans-serif;
        font-size: ${composition.format === "9:16" ? "84px" : "112px"};
        font-weight: 600;
        letter-spacing: -0.02em;
        line-height: 1.05;
        text-align: ${composition.visual === "typography-statement" ? "left" : "center"};
        max-width: ${composition.format === "9:16" ? "900px" : "1400px"};
      }
      .vo-line {
        font-family: '${bodyFont}', sans-serif;
        font-size: ${composition.format === "9:16" ? "32px" : "28px"};
        opacity: 0.7;
        position: absolute;
        bottom: ${composition.format === "9:16" ? "200px" : "120px"};
        left: 0;
        right: 0;
        text-align: center;
        padding: 0 60px;
      }
      /* anti-slop hard constraints — no purple gradients, no card-stacks */
    </style>
  </head>
  <body>
    <div
      id="root"
      data-composition-id="main"
      data-start="0"
      data-duration="${totalDuration}"
      data-width="${width}"
      data-height="${height}"
    >
${sceneClips.join("\n")}
${audioElements.join("\n")}
    </div>

    <script>
      window.__timelines = window.__timelines || {};
      const tl = gsap.timeline({ paused: true });
${tweens.join("\n")}
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
`;
}

// ----------------------------------------------------------------
//  Scene clip builder
// ----------------------------------------------------------------

function buildSceneClip(
  id: string,
  scene: VideoScript["scenes"][number],
  start: number,
  dur: number,
  profile: DesignProfile
): string {
  const onScreen = scene.onScreenText ? escapeHtml(scene.onScreenText) : "";
  const voLine = scene.voLine ? escapeHtml(scene.voLine) : "";

  const headingHtml = onScreen ? `<div class="heading">${onScreen}</div>` : "";
  const voHtml = voLine ? `<div class="vo-line">${voLine}</div>` : "";

  return `      <div
        class="clip scene"
        id="${id}"
        data-start="${start.toFixed(2)}"
        data-duration="${dur.toFixed(2)}"
        data-track-index="${10 + scene.index}"
      >
        ${headingHtml}
        ${voHtml}
      </div>`;
}

function encodeFont(fontName: string): string {
  return fontName.replace(/\s+/g, "+");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
